function test (){
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 1){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 2){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 8){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 12){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 13){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 16){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 17){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 20){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 24){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 31){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 32){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 38){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 41){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 43){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 46){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 49){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 51){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 62){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 63){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 65){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 67){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 68){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 73){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 84){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 87){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 88){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 90){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 91){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 93){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 97){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 102){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 103){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 107){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 113){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 116){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 122){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 124){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 125){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 129){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 132){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 156){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 157){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 164){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 167){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 175){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 185){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 189){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 191){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 192){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 199){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 200){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 201){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 203){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 204){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 210){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 216){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 219){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 224){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 230){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 232){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 233){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 237){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 238){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 239){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 240){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 243){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 245){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 246){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 247){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 248){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 252){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 253){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 254){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 267){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 271){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 278){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 283){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 286){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 133){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 288){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 293){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 294){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 296){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 301){ option.remove();  break; }}
  for(let e of $('#locationID option')){ let option=$(e); if(option.val() == 305){ option.remove();  break; }}
  console.log("DONE");
}; test()

let options = $('#locationID option'); let arr = options.map((_, o) => { return { t:$(o).text(), v:o.value}; }).get(); arr.sort((o1,o2)=>{ return o1.t>o2.t?1:o1.t<o2.t?-1:0;}); options.each((i,o) =>{ o.value = arr[i].v; $(o).text(arr[i].t)});
